### ISSUE TITLE
Apache not starting using xampp control panel when switched to other php version.

### ISSUE THREAD

**Issue by curiousteam** [JackieDo/Xampp-PHP-Switcher#2]
Hi there,

Firstly, I would like to thank you for the solution which you have made. I have been looking a long for something like this.

Unfortunately, Apache is not starting using xampp control panel when switched to other php version which has been added using command 'xphp add "......blah...blah...".

The error message is given below:
```
2:11:59 AM  [Apache] 	Error: Apache shutdown unexpectedly.
2:11:59 AM  [Apache] 	This may be due to a blocked port, missing dependencies, 
2:11:59 AM  [Apache] 	improper privileges, a crash, or a shutdown by another method.
2:11:59 AM  [Apache] 	Press the Logs button to view error logs and check
2:11:59 AM  [Apache] 	the Windows Event Viewer for more clues
2:11:59 AM  [Apache] 	If you need more help, copy and post this
2:11:59 AM  [Apache] 	entire log window on the forums

```
Do you have enough time to look into the matter or is there any solution that may be helpful for me?

Thanks in advance.

P.S: Apache starts perfectly when I switch back to the original PHP version.

**Comment by curiousteam** [comment]
I also would like to inform you that, after installing other PHP versions following your documentation (https://github.com/JackieDo/Xampp-PHP-Switcher#add-other-php-versions-to-your-xampp), I have deleted those unzipped xampp folders.

**Comment by erniegenaw** [comment]
I have the same problem.  It appears the dependencies are not correct.

**Comment by JackieDo** [comment]
To @curiousteam , @erniegenaw :

First, I apologize for the delay in replying and handling the project's issues for quite a while.

Next, I took a close look at the issue you guys posted. I noticed that this error occurs in the following cases:

- Built-in (original) version of Xampp PHP is PHP5/PHP7 and we proceed to add PHP8 version
- Built-in (original) version of Xampp PHP is PHP8 and we proceed to add PHP5/PHP7 version.

**Reason:**

This happens because the "xampp-httpd.conf" file structure of Xampp 8.x version is different from 7.x version and earlier. Meanwhile, this file generation mechanism for additional PHP builds of the project is essentially copying from the original file in the installed Xampp App.

Therefore, I have changed the mechanism for generating this file for new additional builds in the project source code (commit fcfb0cf01f492b6a690cfa3d93731324132300a0) and this has solved the problem.

**Step-by-step troubleshooting for your Switcher system:**

- Update your Xampp PHP Switcher according to the instructions [here](https://github.com/JackieDo/Xampp-PHP-Switcher#updation).
- Replace the contents of the `httpd-xampp-php(x).conf` file in the `apache\conf\extra\` subdirectory of your XAMPP installation directory with the corresponding file in the `src\Templates\xampp-config\` subdirectory of XAMPP PHP Switcher. Remember to replacing the string `{{xamppDir}}` in the content with the path to your Xampp directory.

> Note: `(x)` in the above filename is the major-version of the faulty PHP version.

Hopefully the new version will improve the user experience for you more.

Cordially greet.

**Comment by curiousteam** [comment]
To: @JackieDo 

Thanks again for solving the issue.

I have installed my Xampp using "xampp-windows-x64-7.4.12-0-VC15-installer.exe". I have also updated the Xampp PHP Switcher according to your instructions. After troubleshooting the switcher following your step-by-step guide, I was able to successfully switch between various PHP versions of 7 modules (7.3.24, 7.4.12, and 7.4.22). It works fine with these aforesaid PHP versions.

Unfortunately, I got the following result while trying to switch to PHP 5.6.40:
![error-restarting-apache](https://user-images.githubusercontent.com/29994885/129790223-2718c305-2d1c-4c94-843f-7f1ab1815155.jpg)
Apache does not restart, it just showing that message repeatedly like the screenshot. But it works when I restart the apache manually using the control panel.

And also got the following error for PHP 8.0.9:
![php8-error](https://user-images.githubusercontent.com/29994885/129790249-cf8e749b-9a35-4b77-8d51-36ea076229ce.jpg)
Is it possible to add PHP 8.* versions to my existing Xampp installation with this switcher? I don't wanna reinstall the latest Xampp.

Regards.

**Comment by JackieDo** [comment]
To @curiousteam :

My installed Xampp version is 7.3.12. And i added other PHP builds from 5.6.40 to 8.0.9. Following is the list of builds that have been added to my PHP repository.

![image](https://user-images.githubusercontent.com/9862115/129806850-4cc42d65-dabd-4a79-be84-397ba805f172.png)

All versions I added work perfectly, but yours doesn't. I'm guessing it's because all of my computers have compatible Visual Studio C++ packages installed.

![image](https://user-images.githubusercontent.com/9862115/129807296-44d8b1f5-02a6-48ea-9e20-613bf9439380.png)

Use the command `xphp info` to see the Compiler information for your PHP build version, then you will know which Visual C++ package it needs. (With PHP 5.6.40 is VC++ 2012, and PHP 8.0.9 is VC++ 2019)

![image](https://user-images.githubusercontent.com/9862115/129807646-b0231d97-9814-4230-98df-5ad41f1bb40b.png)

Then download the corresponding Microsoft Visual Studio C++ Redistributable package [here](https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0) and install it.

Hope you solve the problem.

Best regards.
